### ISSUE TITLE
AutoCollection times are closer to 2+ seconds than 1 second

### ISSUE THREAD

**Issue by Hackswell** [Hackswell/GloryOfEfficiency#8]
1. The speed of removing weeds, stones, and wood on the farm is too slow. You need to wait for two seconds to remove them. 

3. It takes two seconds to rummage through trash cans and dig up monuments on the ground, and the collection range cannot be adjusted.

reported by: wandeng

**Comment by mttmmj** [comment]
this is similar with my issue, It takes far more than 1 sec to auto pet my animals.

**Comment by Hackswell** [comment]
I have a feeling there is a LOT of inefficient code.  I just barely got it all running for 1.6.  For BETA 1, I will try finding which updates are taking much longer than 0.1 second and try optimizing them.  I think that some of these routines are taking WAY longer, and preventing updates from finishing within the correct timing.

**Comment by mttmmj** [comment]
Hi, did you realease Alpha4? I can't see the file of Alpha4

**Comment by Hackswell** [comment]
Updated to Update every Nth Tick.   If BalancedMod is TRUE, NthTick is set to 60 (60 ticks ~= 1 second).  If FALSE, then NthTick is set to 15 (0.25 seconds).  This can be edited in the config.json.  Smaller numbers are faster, but will tax your computer more.

**Comment by mttmmj** [comment]
well, I can't see your Alpha4 realease files, could you please realease them so that I can do the test?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sir Woody ***@***.***&gt;; 
发送时间: 2024年4月25日(星期四) 上午10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hackswell/JoysOfEfficiency] AutoCollection times are closer to 2+ seconds than 1 second (Issue #8)














 
Updated to Update every Nth Tick.   If BalancedMod is TRUE, NthTick is set to 60 (60 ticks ~= 1 second).  If FALSE, then NthTick is set to 15 (0.25 seconds).  This can be edited in the config.json.  Smaller numbers are faster, but will tax your computer more.

**Comment by Hackswell** [comment]
> Hi, did you realease Alpha4? I can't see the file of Alpha4

Hoping to release TOMORROW.  Just cleaning up and finishing documentation and sanity checks.

**Comment by mttmmj** [comment]
OK，Thanks a lot! Really look forward to it!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sir Woody ***@***.***&gt;; 
发送时间: 2024年4月25日(星期四) 上午10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hackswell/JoysOfEfficiency] AutoCollection times are closer to 2+ seconds than 1 second (Issue #8)














  
Hi, did you realease Alpha4? I can't see the file of Alpha4
  
Hoping to release TOMORROW.  Just cleaning up and finishing documentation and sanity checks.
